package forme.klub;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.MatteBorder;
import klijent.Klijent;
import model.TipNaloga;
import model.VeslackiKlub;

/**
 *
 * @author luka
 */
public class IzmeniPodatkeVKForma extends javax.swing.JDialog {

    public IzmeniPodatkeVKForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicijalnoRenderovanje();
        
        setLocationRelativeTo(this);
        
        VeslackiKlub ulogovaniKlub = (VeslackiKlub) Klijent.getInstance().getUlogovaniNalog();
        System.out.println(ulogovaniKlub);
        nazivInput.setText(ulogovaniKlub.getNaziv());
        adresaInput.setText(ulogovaniKlub.getAdresa());
        emailInput.setText(ulogovaniKlub.getEmail());
        telefonInput.setText(ulogovaniKlub.getTelefon().substring(4));
        korisnickoImeInput.setText(ulogovaniKlub.getKorisnickoIme());
        sifraInput.setText(ulogovaniKlub.getSifra());
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        
        setVisible(true);

        
    }

    public IzmeniPodatkeVKForma(JFrame roditelj) {
        super(roditelj, "Registracija korisnika", true);
        initComponents();
        inicijalnoRenderovanje();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        izaberiteTipLabel = new javax.swing.JLabel();
        tipNalogaComboBox = new javax.swing.JComboBox<>();
        glavnaFormaPanel1 = new forme.utils.GlavnaFormaPanel();
        obrisiNalog = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        potvrdaButton = new javax.swing.JButton();
        nazivLabel = new javax.swing.JLabel();
        adresaLabel = new javax.swing.JLabel();
        adresaInput = new javax.swing.JTextField();
        nazivInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        telefonLabel = new javax.swing.JLabel();
        telefonInput = new javax.swing.JTextField();
        telefonComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        potvrdaSifreLabel = new javax.swing.JLabel();
        korisnickoImeInput = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        korisnickoImeLabel = new javax.swing.JLabel();
        potvrdaSifreInput = new javax.swing.JPasswordField();
        sifraLabel = new javax.swing.JLabel();
        sifraInput = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        greskaPotvrdaLabel = new javax.swing.JLabel();
        greskaSifraLabel = new javax.swing.JLabel();
        greskaTelefonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registracija");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        titlePanel.setBackground(new java.awt.Color(13, 146, 244));

        titleLabel.setFont(new java.awt.Font("JetBrains Mono", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Izmenite podatke");

        izaberiteTipLabel.setFont(new java.awt.Font("JetBrains Mono", 3, 24)); // NOI18N
        izaberiteTipLabel.setForeground(new java.awt.Color(255, 255, 255));
        izaberiteTipLabel.setText("Ažurirajte vaš nalog");

        tipNalogaComboBox.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        tipNalogaComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tipNalogaComboBox.setEnabled(false);

        obrisiNalog.setBackground(new java.awt.Color(238, 236, 236));
        obrisiNalog.setFont(new java.awt.Font("JetBrains Mono", 1, 19)); // NOI18N
        obrisiNalog.setForeground(new java.awt.Color(255, 51, 51));
        obrisiNalog.setText("Obriši nalog");
        obrisiNalog.setToolTipText("");
        obrisiNalog.setBorder(null);
        obrisiNalog.setFocusPainted(false);
        obrisiNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiNalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavnaFormaPanel1Layout = new javax.swing.GroupLayout(glavnaFormaPanel1);
        glavnaFormaPanel1.setLayout(glavnaFormaPanel1Layout);
        glavnaFormaPanel1Layout.setHorizontalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavnaFormaPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(obrisiNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        glavnaFormaPanel1Layout.setVerticalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(obrisiNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(izaberiteTipLabel))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(tipNalogaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(izaberiteTipLabel)
                .addGap(40, 40, 40)
                .addComponent(tipNalogaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        getContentPane().add(titlePanel);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setPreferredSize(new java.awt.Dimension(600, 800));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/user(5).png"))); // NOI18N
        jLabel1.setText("Podaci");
        infoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        infoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));
        infoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 46, -1, -1));

        potvrdaButton.setBackground(new java.awt.Color(13, 146, 244));
        potvrdaButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        potvrdaButton.setForeground(new java.awt.Color(255, 255, 255));
        potvrdaButton.setText("Potvrdi Izmenu");
        potvrdaButton.setBorder(null);
        potvrdaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdaButtonActionPerformed(evt);
            }
        });
        infoPanel.add(potvrdaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 689, 431, 60));

        nazivLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        nazivLabel.setText("Naziv");
        infoPanel.add(nazivLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 80, -1));

        adresaLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        adresaLabel.setText("Adresa");
        infoPanel.add(adresaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 90, -1));

        adresaInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        adresaInput.setForeground(new java.awt.Color(153, 153, 153));
        adresaInput.setText("Unesite adresu...");
        adresaInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        adresaInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adresaInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adresaInputFocusLost(evt);
            }
        });
        infoPanel.add(adresaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 200, -1));

        nazivInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        nazivInput.setForeground(new java.awt.Color(153, 153, 153));
        nazivInput.setText("Unesite naziv...");
        nazivInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        nazivInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nazivInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nazivInputFocusLost(evt);
            }
        });
        infoPanel.add(nazivInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, -1));

        emailLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        emailLabel.setText("Email");
        infoPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));

        emailInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        emailInput.setForeground(new java.awt.Color(153, 153, 153));
        emailInput.setText("Unesite email...");
        emailInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        emailInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailInputFocusLost(evt);
            }
        });
        infoPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 308, 200, -1));

        telefonLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        telefonLabel.setText("Telefon");
        infoPanel.add(telefonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 258, -1, -1));

        telefonInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        telefonInput.setForeground(new java.awt.Color(153, 153, 153));
        telefonInput.setText("6512345");
        telefonInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonInputFocusLost(evt);
            }
        });
        telefonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonInputActionPerformed(evt);
            }
        });
        infoPanel.add(telefonInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 304, 110, -1));

        telefonComboBox.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        telefonComboBox.setForeground(new java.awt.Color(153, 153, 153));
        telefonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+381", "+1", "+44", "+61", "+91", "+49", "+33", "+39", "+34", "+52", "+55", "+86", "+81", "+82", "+27", "+7", "+20", "+90", "+54", "+966", "+234", "+92", "+62", "+66", "+64", "+63", "+46", "+31", "+32", "+41", "+351", "+30", "+972", "+84", "+56", "+48", "+65", "+60", "+380" }));
        telefonComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonComboBoxActionPerformed(evt);
            }
        });
        infoPanel.add(telefonComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 304, 100, -1));

        jLabel10.setForeground(new java.awt.Color(251, 51, 51));
        jLabel10.setText("*");
        infoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 20, -1));

        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setText("*");
        infoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 33, -1));

        jLabel12.setForeground(new java.awt.Color(251, 51, 51));
        jLabel12.setText("*");
        infoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 10, -1));

        jLabel13.setForeground(new java.awt.Color(251, 51, 51));
        jLabel13.setText("*");
        infoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        potvrdaSifreLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        potvrdaSifreLabel.setText("Potvrda šifre");
        infoPanel.add(potvrdaSifreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        korisnickoImeInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        korisnickoImeInput.setForeground(new java.awt.Color(153, 153, 153));
        korisnickoImeInput.setText("Unesite korisnika...");
        korisnickoImeInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        korisnickoImeInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                korisnickoImeInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                korisnickoImeInputFocusLost(evt);
            }
        });
        korisnickoImeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnickoImeInputActionPerformed(evt);
            }
        });
        infoPanel.add(korisnickoImeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 419, 230, -1));

        jLabel15.setForeground(new java.awt.Color(251, 51, 51));
        jLabel15.setText("*");
        infoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 15, -1));

        korisnickoImeLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        korisnickoImeLabel.setText("Korisničko ime");
        infoPanel.add(korisnickoImeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 373, 210, -1));

        potvrdaSifreInput.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        potvrdaSifreInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        infoPanel.add(potvrdaSifreInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 583, 200, -1));

        sifraLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        sifraLabel.setText("Šifra");
        infoPanel.add(sifraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 537, 80, -1));

        sifraInput.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        sifraInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        infoPanel.add(sifraInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 583, 200, -1));

        jLabel18.setForeground(new java.awt.Color(251, 51, 51));
        jLabel18.setText("*");
        infoPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 15, -1));

        jLabel19.setForeground(new java.awt.Color(251, 51, 51));
        jLabel19.setText("*");
        infoPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 15, -1));

        greskaPotvrdaLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        greskaPotvrdaLabel.setForeground(new java.awt.Color(255, 51, 51));
        greskaPotvrdaLabel.setText("Greška pri potvrdi šifre");
        infoPanel.add(greskaPotvrdaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 280, -1));

        greskaSifraLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        greskaSifraLabel.setForeground(new java.awt.Color(255, 51, 51));
        greskaSifraLabel.setText("Greška pri unosu šifre");
        infoPanel.add(greskaSifraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 260, -1));

        greskaTelefonLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        greskaTelefonLabel.setForeground(new java.awt.Color(255, 51, 51));
        greskaTelefonLabel.setText("Greška pri unosu telefona");
        infoPanel.add(greskaTelefonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 280, -1));

        getContentPane().add(infoPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void potvrdaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdaButtonActionPerformed
        
        try{
            
        
        boolean greska = false;
        // Promena boje nazivInput polja pri gresci
        if (nazivInput.getText().isEmpty() || nazivInput.getText().equals("Unesite naziv...")) {
            nazivInput.setForeground(new Color(255, 51, 51));
            nazivInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
            greska = true;
        }
        // Promena boje adresaInput polja pri gresci
        if (adresaInput.getText().isEmpty() || adresaInput.getText().equals("Unesite adresu...")) {
            adresaInput.setForeground(new Color(255, 51, 51));
            adresaInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
            greska = true;
        }
        // Promena boje emailInput polja pri gresci
        if (emailInput.getText().isEmpty() || emailInput.getText().equals("Unesite email...")) {
            emailInput.setForeground(new Color(255, 51, 51));
            emailInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
            greska = true;
        }
        // Promena boje telefonInput polja pri gresci
        if (telefonInput.getText().isEmpty() || telefonInput.getText().equals("6512345")) {
            telefonInput.setForeground(new Color(255, 51, 51));
            greskaTelefonLabel.setVisible(true);
            greska = true;
        }
        // Promena boje korisnickoImeInput polja pri gresci
        if (korisnickoImeInput.getText().isEmpty() || korisnickoImeInput.getText().equals("Unesite korisnika...")) {
            korisnickoImeInput.setForeground(new Color(255, 51, 51));
            korisnickoImeInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
            greska = true;
        }
        // Renderovanje poruke greske za pogresan format šifre
        if(sifraInput.getText().isEmpty() || sifraInput.getText().length() < 6){
            greskaSifraLabel.setVisible(true);
            greska = true;
        }
        // Renderovanje poruke greske za pogresnu potvrdu šifre
        if(potvrdaSifreInput.getText().isEmpty() || !potvrdaSifreInput.getText().equals(sifraInput.getText())){
            greskaPotvrdaLabel.setVisible(true);
            greska = true;
        }
        
//         Ako nije napravljena greska kreira se novi veslački klub
        if(!greska){
            VeslackiKlub klub = (VeslackiKlub) Klijent.getInstance().getUlogovaniNalog();
            VeslackiKlub azuriraniKlub = Klijent.getInstance().azuirirajVeslackiKlub(new VeslackiKlub(klub.getId(),nazivInput.getText(),adresaInput.getText(),emailInput.getText(),
                    ((String) telefonComboBox.getSelectedItem()) + telefonInput.getText(), korisnickoImeInput.getText(),sifraInput.getText()));
            if(azuriraniKlub != null){
                JOptionPane.showMessageDialog(this,"Podaci naloga su ažurirani","Uspešno ažuiriranje naloga", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(this,"Greska pri potvrdi promena u bazi","Greska",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Greska, uneti podaci nisu ispavni, probajte ponovo.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }


    }//GEN-LAST:event_potvrdaButtonActionPerformed

    private void telefonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonInputActionPerformed

    private void telefonComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonComboBoxActionPerformed

    private void nazivInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazivInputFocusGained
        if (nazivInput.getText().equals("Unesite naziv...")) {
            nazivInput.setText("");
        }
    }//GEN-LAST:event_nazivInputFocusGained

    private void nazivInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazivInputFocusLost
        if (nazivInput.getText().isEmpty()) {
            nazivInput.setText("Unesite naziv...");
        }
    }//GEN-LAST:event_nazivInputFocusLost

    private void adresaInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresaInputFocusGained
        if (adresaInput.getText().equals("Unesite adresu...")) {
            adresaInput.setText("");
        }
    }//GEN-LAST:event_adresaInputFocusGained

    private void emailInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusGained
        // TODO add your handling code here:
        if (emailInput.getText().equals("Unesite email...")) {
            emailInput.setText("");
        }
    }//GEN-LAST:event_emailInputFocusGained

    private void emailInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusLost
        // TODO add your handling code here:
        if (emailInput.getText().isEmpty()) {
            emailInput.setText("Unesite email...");
        }
    }//GEN-LAST:event_emailInputFocusLost

    private void telefonInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonInputFocusGained
        // TODO add your handling code here:
        if (telefonInput.getText().equals("6512345")) {
            telefonInput.setText("");
        }
    }//GEN-LAST:event_telefonInputFocusGained

    private void telefonInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonInputFocusLost
        // TODO add your handling code here:
        if (telefonInput.getText().isEmpty()) {
            telefonInput.setText("6512345");
        }
    }//GEN-LAST:event_telefonInputFocusLost

    private void korisnickoImeInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_korisnickoImeInputFocusGained
        // TODO add your handling code here:
        if (korisnickoImeInput.getText().equals("Unesite korisnika...")) {
            korisnickoImeInput.setText("");
        }
    }//GEN-LAST:event_korisnickoImeInputFocusGained

    private void korisnickoImeInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_korisnickoImeInputFocusLost
        // TODO add your handling code here:
        if (korisnickoImeInput.getText().isEmpty()) {
            korisnickoImeInput.setText("Unesite korisnika...");
        }
    }//GEN-LAST:event_korisnickoImeInputFocusLost

    private void adresaInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresaInputFocusLost
        // TODO add your handling code here:
        if(adresaInput.getText().isEmpty()){
            adresaInput.setText("Unesite adresa...");
        }
    }//GEN-LAST:event_adresaInputFocusLost

    private void korisnickoImeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnickoImeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnickoImeInputActionPerformed

    private void obrisiNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiNalogActionPerformed
        // TODO add your handling code here:
        
        try{
        
        int odgovor = JOptionPane.showConfirmDialog(this,"Da li ste sigurni da želite da obrišete nalog?");

        if(odgovor == JOptionPane.YES_OPTION){
            
            Klijent.getInstance().obrisiVeslackiKlub((Integer) Klijent.getInstance().getUlogovaniNalog().getId());
            Klijent.getInstance().setUlogovaniNalog(null);
            this.dispose();
            Klijent.getInstance().setOdjavaSignal(true);
            
        }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_obrisiNalogActionPerformed

    
    private void inicijalnoRenderovanje(){
        // Inicijalno sakriva poruke gresaka pri pokretanju forme
        tipNalogaComboBox.addItem(TipNaloga.VESLACKI_KLUB);
        
        greskaTelefonLabel.setVisible(false);
        greskaSifraLabel.setVisible(false);
        greskaPotvrdaLabel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaInput;
    private javax.swing.JLabel adresaLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel1;
    private javax.swing.JLabel greskaPotvrdaLabel;
    private javax.swing.JLabel greskaSifraLabel;
    private javax.swing.JLabel greskaTelefonLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel izaberiteTipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField korisnickoImeInput;
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JTextField nazivInput;
    private javax.swing.JLabel nazivLabel;
    private javax.swing.JButton obrisiNalog;
    private javax.swing.JButton potvrdaButton;
    private javax.swing.JPasswordField potvrdaSifreInput;
    private javax.swing.JLabel potvrdaSifreLabel;
    private javax.swing.JPasswordField sifraInput;
    private javax.swing.JLabel sifraLabel;
    private javax.swing.JComboBox<String> telefonComboBox;
    private javax.swing.JTextField telefonInput;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JComboBox<TipNaloga> tipNalogaComboBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
