package forme.klub;

import forme.tableModeli.AgencijaTableModel;
import forme.tableModeli.StavkaPonudeTableModel;
import forme.tableModeli.VeslacTableModel;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import klijent.Klijent;
import model.PonudaVeslaca;
import model.StavkaPonude;
import model.Veslac;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author lukad
 */
public class IzmeniPonuduForma extends javax.swing.JDialog {
    
    private static final Logger logger = LogManager.getRootLogger();
    private PonudaVeslaca ponudaVeslaca;
    private List<Veslac> veslaciVanPonude;
    private List<StavkaPonude> obrisaneStavke = new LinkedList<>();
    private List<StavkaPonude> dodateStavke = new LinkedList<>();
    private List<StavkaPonude> stavkePonude;
    private Stack<Integer> izbaceniRb = new Stack<>();
    
    private VeslacTableModel vptm;
    private StavkaPonudeTableModel sptm;
    private AgencijaTableModel atm;
    
    private int rb;
    
    public IzmeniPonuduForma(java.awt.Frame parent, boolean modal, PonudaVeslaca ponudaVeslaca) {
        super(parent, modal);
        
        setResizable(false);
        try {
            initComponents();
            this.ponudaVeslaca = ponudaVeslaca;
            stavkePonude = ponudaVeslaca.getStavke();
            rb = ponudaVeslaca.getStavke().size();
            
//            veslaciVanPonude = Klijent.getInstance().vratiListuSviVeslaci(ponudaVeslaca.getIdKluba());
//            for (StavkaPonude stavka : stavkePonude) {
//                if(veslaciVanPonude.contains(stavka.getVeslac())){
//                    veslaciVanPonude.remove(stavka.getVeslac());
//                }
//            }
            
//            veslaciTable.setModel(new VeslacTableModel(veslaciVanPonude));
//            stavkeTable.setModel(new StavkaPonudeTableModel(stavkePonude));
//            agencijaTable.setModel(new AgencijaTableModel(Klijent.getInstance().vratiSveAgencije()));
            
            vptm = (VeslacTableModel) veslaciTable.getModel();
            sptm = (StavkaPonudeTableModel) stavkeTable.getModel();
            atm = (AgencijaTableModel) agencijaTable.getModel();
            
            
            
        } catch (Exception ex) {
            logger.error(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        glavnaFormaPanel25 = new forme.utils.GlavnaFormaPanel();
        jLabel21 = new javax.swing.JLabel();
        glavnaFormaPanel1 = new forme.utils.GlavnaFormaPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        veslaciTable = new forme.utils.GlavnaFormaTable();
        dodajStavkuButton = new javax.swing.JButton();
        glavnaFormaPanel2 = new forme.utils.GlavnaFormaPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stavkeTable = new forme.utils.GlavnaFormaTable();
        obrisiStavkuButton = new javax.swing.JButton();
        glavnaFormaPanel3 = new forme.utils.GlavnaFormaPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        agencijaTable = new forme.utils.GlavnaFormaTable();
        dodajStavkuButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(221, 221, 221));

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/document(2).png"))); // NOI18N
        jLabel21.setText("Ažuriranje stavki u ponudu veslača");
        jLabel21.setFont(new java.awt.Font("JetBrains Mono", 3, 24)); // NOI18N

        javax.swing.GroupLayout glavnaFormaPanel25Layout = new javax.swing.GroupLayout(glavnaFormaPanel25);
        glavnaFormaPanel25.setLayout(glavnaFormaPanel25Layout);
        glavnaFormaPanel25Layout.setHorizontalGroup(
            glavnaFormaPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        glavnaFormaPanel25Layout.setVerticalGroup(
            glavnaFormaPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        veslaciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(veslaciTable);

        dodajStavkuButton.setText("Dodaj u stavke");
        dodajStavkuButton.setBackground(new java.awt.Color(14, 146, 244));
        dodajStavkuButton.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        dodajStavkuButton.setForeground(new java.awt.Color(255, 255, 255));
        dodajStavkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStavkuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavnaFormaPanel1Layout = new javax.swing.GroupLayout(glavnaFormaPanel1);
        glavnaFormaPanel1.setLayout(glavnaFormaPanel1Layout);
        glavnaFormaPanel1Layout.setHorizontalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavnaFormaPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dodajStavkuButton)
                .addContainerGap())
        );
        glavnaFormaPanel1Layout.setVerticalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dodajStavkuButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        stavkeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(stavkeTable);

        obrisiStavkuButton.setText("Obriši iz stavki");
        obrisiStavkuButton.setBackground(new java.awt.Color(14, 146, 244));
        obrisiStavkuButton.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        obrisiStavkuButton.setForeground(new java.awt.Color(255, 255, 255));
        obrisiStavkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiStavkuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavnaFormaPanel2Layout = new javax.swing.GroupLayout(glavnaFormaPanel2);
        glavnaFormaPanel2.setLayout(glavnaFormaPanel2Layout);
        glavnaFormaPanel2Layout.setHorizontalGroup(
            glavnaFormaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavnaFormaPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(obrisiStavkuButton)
                .addContainerGap())
        );
        glavnaFormaPanel2Layout.setVerticalGroup(
            glavnaFormaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obrisiStavkuButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        agencijaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(agencijaTable);

        dodajStavkuButton2.setText("Ažuriraj ponudu");
        dodajStavkuButton2.setBackground(new java.awt.Color(14, 146, 244));
        dodajStavkuButton2.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        dodajStavkuButton2.setForeground(new java.awt.Color(255, 255, 255));
        dodajStavkuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStavkuButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavnaFormaPanel3Layout = new javax.swing.GroupLayout(glavnaFormaPanel3);
        glavnaFormaPanel3.setLayout(glavnaFormaPanel3Layout);
        glavnaFormaPanel3Layout.setHorizontalGroup(
            glavnaFormaPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavnaFormaPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dodajStavkuButton2)
                .addContainerGap())
        );
        glavnaFormaPanel3Layout.setVerticalGroup(
            glavnaFormaPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dodajStavkuButton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(glavnaFormaPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glavnaFormaPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(glavnaFormaPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(glavnaFormaPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(glavnaFormaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(glavnaFormaPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajStavkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStavkuButtonActionPerformed

        try{

            if (veslaciTable.getSelectedRow() != -1) {
                int idVeslaca = (int) veslaciTable.getValueAt(veslaciTable.getSelectedRow(), 0);
                StavkaPonude s = new StavkaPonude();
                
                Veslac izabraniVeslac = veslaciVanPonude.stream().filter(v -> v.getId() == idVeslaca).findFirst().get();
                s.setVeslac(izabraniVeslac);
                Date datumUpisa = izabraniVeslac.getDatumUpisa();
                LocalDate datumUpisaLD = datumUpisa.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                Period p = Period.between(datumUpisaLD, LocalDate.now());
                int years = p.getYears();
                s.setGodineTreniranja(years);

                s.setPonudaVeslaca(ponudaVeslaca);
                

                if (izbaceniRb.isEmpty()) {
                    s.setRb(++rb);
                } else {
                    rb = izbaceniRb.pop();
                    s.setRb(rb);             
                }
                
                sptm.dodajStavku(s);
                dodateStavke.add(s);
                obrisaneStavke.remove(s);
                vptm.obrisiVeslaca(s.getVeslac().getId());
                                

            } else {
                JOptionPane.showMessageDialog(this, "Veslac nije selektovan,selektujte veslaca da bi kreirali stavku ponude", "Greska", JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception ex){
            logger.error(ex.getMessage());
        }

    }//GEN-LAST:event_dodajStavkuButtonActionPerformed

    private void obrisiStavkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiStavkuButtonActionPerformed
        // TODO add your handling code here:
        if(stavkeTable.getSelectedRow() != -1) {
            int rba = (int) stavkeTable.getValueAt(stavkeTable.getSelectedRow(), 0);
            izbaceniRb.add(rba);
            StavkaPonude stavka = stavkePonude.stream().filter(s -> s.getRb() == rba).findFirst().get();
            Veslac veslac = stavka.getVeslac();
            
            vptm.dodajVeslaca(veslac);
            sptm.obrisiStavku(rba);
            
            obrisaneStavke.add(stavka);
            dodateStavke.remove(stavka);
        } 
    }//GEN-LAST:event_obrisiStavkuButtonActionPerformed

    private void dodajStavkuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStavkuButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if(obrisaneStavke.isEmpty() && dodateStavke.isEmpty()) return;         
            
            PonudaVeslaca azuriranaPonuda = Klijent.getInstance().promeniPonudu(ponudaVeslaca);
            JOptionPane.showMessageDialog(this, "Uspesno kreiranje ponude veslaca","Uspeh",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex,"Greska pri azuriranju ponude veslaca", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_dodajStavkuButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private forme.utils.GlavnaFormaTable agencijaTable;
    private javax.swing.JButton dodajStavkuButton;
    private javax.swing.JButton dodajStavkuButton2;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel1;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel2;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel25;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel3;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton obrisiStavkuButton;
    private forme.utils.GlavnaFormaTable stavkeTable;
    private forme.utils.GlavnaFormaTable veslaciTable;
    // End of variables declaration//GEN-END:variables
}
