package forme.veslac;

import com.formdev.flatlaf.FlatLightLaf;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import kontroler.Kontroler;
import model.KategorijaVeslaca;
import model.Veslac;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author luka
 */
public class IzmeniVeslacForma extends javax.swing.JDialog {
    
    private Veslac veslac;
    
    private static final Logger logger = LogManager.getRootLogger();
    
    public IzmeniVeslacForma(java.awt.Frame parent, boolean modal,Veslac veslac) {
        super(parent, modal);
        initComponents();
        inicijalnoRenderovanje();
        
        setLocationRelativeTo(null);
        
        this.veslac = veslac;
        
        imePrezimeInput.setText(veslac.getImePrezime());
        visinaInput.setText(String.valueOf(veslac.getVisina()));
        tezinaInput.setText(String.valueOf(veslac.getTezina()));
        if(veslac.getKategorija().equals(KategorijaVeslaca.JUNIOR)){
            kategorijaComboBox.setSelectedItem(KategorijaVeslaca.JUNIOR);
        }else{
            kategorijaComboBox.setSelectedItem(KategorijaVeslaca.KADET);
        }
        
        rodjenjeDatePicker.setDate(veslac.getDatumRodjenja().toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate());
        upisDatePicker.setDate(veslac.getDatumUpisa().toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate());
        
        
        najboljeVremeInput.setText(String.valueOf(veslac.getNajboljeVreme()));
//        idKlubaInput.setText(String.valueOf(veslac.getIdKluba()));
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            logger.error(ex.getMessage());
        }
        
        setVisible(true);

        
    }

    public IzmeniVeslacForma(JFrame roditelj) {
        super(roditelj, "Registracija korisnika", true);
        initComponents();
        inicijalnoRenderovanje();
        
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        izaberiteTipLabel = new javax.swing.JLabel();
        glavnaFormaPanel1 = new forme.utils.GlavnaFormaPanel();
        obrisiVeslacBtn = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        potvrdiAzuriranjeButton = new javax.swing.JButton();
        nazivLabel = new javax.swing.JLabel();
        adresaLabel = new javax.swing.JLabel();
        tezinaInput = new javax.swing.JTextField();
        imePrezimeInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        visinaInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        korisnickoImeLabel = new javax.swing.JLabel();
        kategorijaComboBox = new javax.swing.JComboBox<>();
        adresaLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        najboljeVremeInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rodjenjeDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        upisDatePicker = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registracija");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        titlePanel.setBackground(new java.awt.Color(13, 146, 244));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Izmenite podatke");
        titleLabel.setFont(new java.awt.Font("JetBrains Mono", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));

        izaberiteTipLabel.setText("Ažurirajte veslača");
        izaberiteTipLabel.setFont(new java.awt.Font("JetBrains Mono", 3, 24)); // NOI18N
        izaberiteTipLabel.setForeground(new java.awt.Color(255, 255, 255));

        obrisiVeslacBtn.setText("Obriši veslača");
        obrisiVeslacBtn.setBackground(new java.awt.Color(238, 236, 236));
        obrisiVeslacBtn.setBorder(null);
        obrisiVeslacBtn.setFocusPainted(false);
        obrisiVeslacBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 19)); // NOI18N
        obrisiVeslacBtn.setForeground(new java.awt.Color(255, 51, 51));
        obrisiVeslacBtn.setToolTipText("");
        obrisiVeslacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiVeslacBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavnaFormaPanel1Layout = new javax.swing.GroupLayout(glavnaFormaPanel1);
        glavnaFormaPanel1.setLayout(glavnaFormaPanel1Layout);
        glavnaFormaPanel1Layout.setHorizontalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavnaFormaPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(obrisiVeslacBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        glavnaFormaPanel1Layout.setVerticalGroup(
            glavnaFormaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavnaFormaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(obrisiVeslacBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izaberiteTipLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(izaberiteTipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(glavnaFormaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        getContentPane().add(titlePanel);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setPreferredSize(new java.awt.Dimension(600, 800));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/user(5).png"))); // NOI18N
        jLabel1.setText("Podaci");
        infoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        infoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));
        infoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 46, -1, -1));

        potvrdiAzuriranjeButton.setText("Potvrdi Izmenu");
        potvrdiAzuriranjeButton.setBackground(new java.awt.Color(13, 146, 244));
        potvrdiAzuriranjeButton.setBorder(null);
        potvrdiAzuriranjeButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        potvrdiAzuriranjeButton.setForeground(new java.awt.Color(255, 255, 255));
        potvrdiAzuriranjeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdiAzuriranjeButtonActionPerformed(evt);
            }
        });
        infoPanel.add(potvrdiAzuriranjeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 689, 431, 60));

        nazivLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        nazivLabel.setText("Ime prezime");
        infoPanel.add(nazivLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        adresaLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        adresaLabel.setText("Težina");
        infoPanel.add(adresaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, -1));

        tezinaInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        tezinaInput.setForeground(new java.awt.Color(153, 153, 153));
        tezinaInput.setText("Unesite težinu...");
        tezinaInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        tezinaInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tezinaInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tezinaInputFocusLost(evt);
            }
        });
        infoPanel.add(tezinaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 210, -1));

        imePrezimeInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        imePrezimeInput.setForeground(new java.awt.Color(153, 153, 153));
        imePrezimeInput.setText("Unesite ime...");
        imePrezimeInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        imePrezimeInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imePrezimeInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                imePrezimeInputFocusLost(evt);
            }
        });
        infoPanel.add(imePrezimeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, -1));

        emailLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        emailLabel.setText("Visina");
        infoPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, -1));

        visinaInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        visinaInput.setForeground(new java.awt.Color(153, 153, 153));
        visinaInput.setText("Unesite visinu...");
        visinaInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        visinaInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                visinaInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                visinaInputFocusLost(evt);
            }
        });
        infoPanel.add(visinaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 200, -1));

        jLabel10.setForeground(new java.awt.Color(251, 51, 51));
        jLabel10.setText("*");
        infoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 20, -1));

        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setText("*");
        infoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 33, -1));

        jLabel12.setForeground(new java.awt.Color(251, 51, 51));
        jLabel12.setText("*");
        infoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 10, -1));

        korisnickoImeLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        korisnickoImeLabel.setText("Kategorija");
        infoPanel.add(korisnickoImeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 150, -1));

        kategorijaComboBox.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        infoPanel.add(kategorijaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 200, 30));

        adresaLabel1.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        adresaLabel1.setText("Težina");
        infoPanel.add(adresaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, -1));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono NL", 2, 24)); // NOI18N
        jLabel4.setText("Datum rodjenja");
        infoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, 30));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        jLabel5.setText("Najbolje vreme");
        infoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 220, 40));

        najboljeVremeInput.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        najboljeVremeInput.setForeground(new java.awt.Color(153, 153, 153));
        najboljeVremeInput.setText("Unesite vreme...");
        najboljeVremeInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        najboljeVremeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                najboljeVremeInputActionPerformed(evt);
            }
        });
        infoPanel.add(najboljeVremeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 220, 30));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        jLabel6.setText("Datum upisa");
        infoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 200, 40));

        jLabel13.setForeground(new java.awt.Color(251, 51, 51));
        jLabel13.setText("*");
        infoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 10, -1));

        jLabel16.setForeground(new java.awt.Color(251, 51, 51));
        jLabel16.setText("*");
        infoPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 15, -1));

        jLabel14.setForeground(new java.awt.Color(251, 51, 51));
        jLabel14.setText("*");
        infoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 10, -1));

        jLabel17.setForeground(new java.awt.Color(251, 51, 51));
        jLabel17.setText("*");
        infoPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 10, -1));

        rodjenjeDatePicker.setBackground(new java.awt.Color(221, 221, 221));
        infoPanel.add(rodjenjeDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 210, -1));

        upisDatePicker.setBackground(new java.awt.Color(221, 221, 221));
        infoPanel.add(upisDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 560, 200, -1));

        getContentPane().add(infoPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visinaInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_visinaInputFocusLost
        // TODO add your handling code here:
        if (visinaInput.getText().isEmpty()) {
            visinaInput.setText("Unesite email...");
        }
    }//GEN-LAST:event_visinaInputFocusLost

    private void visinaInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_visinaInputFocusGained
        // TODO add your handling code here:
        if (visinaInput.getText().equals("Unesite email...")) {
            visinaInput.setText("");
        }
    }//GEN-LAST:event_visinaInputFocusGained

    private void imePrezimeInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imePrezimeInputFocusLost
        if (imePrezimeInput.getText().isEmpty()) {
            imePrezimeInput.setText("Unesite naziv...");
        }
    }//GEN-LAST:event_imePrezimeInputFocusLost

    private void imePrezimeInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imePrezimeInputFocusGained
        if (imePrezimeInput.getText().equals("Unesite naziv...")) {
            imePrezimeInput.setText("");
        }
    }//GEN-LAST:event_imePrezimeInputFocusGained

    private void tezinaInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tezinaInputFocusLost
        // TODO add your handling code here:
        if(tezinaInput.getText().isEmpty()){
            tezinaInput.setText("Unesite adresa...");
        }
    }//GEN-LAST:event_tezinaInputFocusLost

    private void tezinaInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tezinaInputFocusGained
        if (tezinaInput.getText().equals("Unesite adresu...")) {
            tezinaInput.setText("");
        }
    }//GEN-LAST:event_tezinaInputFocusGained

    private void potvrdiAzuriranjeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdiAzuriranjeButtonActionPerformed
        if(rodjenjeDatePicker.getDate() != null && upisDatePicker.getDate() != null
                && !imePrezimeInput.getText().isEmpty() && !visinaInput.getText().isEmpty() 
                && !tezinaInput.getText().isEmpty() && !najboljeVremeInput.getText().isEmpty() 
                ){
            
            LocalDate datumRodjLD =  rodjenjeDatePicker.getDate();
            LocalDate datumUpisLD = upisDatePicker.getDate();
            
            Date datumRodj = Date.from(datumRodjLD.atStartOfDay(ZoneId.systemDefault()).toInstant());
            Date datumUpis = Date.from(datumUpisLD.atStartOfDay(ZoneId.systemDefault()).toInstant());
            
            veslac.setImePrezime(imePrezimeInput.getText());
            veslac.setDatumRodjenja(datumRodj);
            veslac.setVisina(Float.parseFloat(visinaInput.getText()));
            veslac.setTezina(Float.parseFloat(tezinaInput.getText()));
            veslac.setKategorija((KategorijaVeslaca) kategorijaComboBox.getSelectedItem());
//            String najboljeVreme = Math.floor(Float.parseFloat(najboljeVremeInput.getText()) / 60) + ":" + Math.floor(Float.parseFloat(najboljeVremeInput.getText()) % 60);
            veslac.setBMI(veslac.getTezina() / (veslac.getVisina() * veslac.getVisina()));
//            veslac.setNajboljeVreme(Float.parseFloat(najboljeVremeInput.getText()));
            veslac.setNajboljeVreme(Float.parseFloat(najboljeVremeInput.getText()));
            veslac.setDatumUpisa(datumUpis);
//            veslac.setIdKluba(Integer.parseInt(idKlubaInput.getText()));
            
            try {
                Kontroler.getInstance().azurirajVeslaca(veslac);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Greska pri azuriranju" + ex,"Greska",JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Sva polja nisu popunjena","Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_potvrdiAzuriranjeButtonActionPerformed

    private void najboljeVremeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_najboljeVremeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_najboljeVremeInputActionPerformed

    private void obrisiVeslacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiVeslacBtnActionPerformed
        // TODO add your handling code here:

        try{
            Kontroler.getInstance().obrisiVeslaca(veslac.getId());
            JOptionPane.showMessageDialog(this, "Sistem je obrisao veslača", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
//            this.dispose();

        }catch(Exception ex){
            logger.error(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše veslača", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_obrisiVeslacBtnActionPerformed

    
    private void inicijalnoRenderovanje(){
        // Inicijalno sakriva poruke gresaka pri pokretanju forme
        kategorijaComboBox.addItem(KategorijaVeslaca.JUNIOR);
        kategorijaComboBox.addItem(KategorijaVeslaca.KADET);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresaLabel;
    private javax.swing.JLabel adresaLabel1;
    private javax.swing.JLabel emailLabel;
    private forme.utils.GlavnaFormaPanel glavnaFormaPanel1;
    private javax.swing.JTextField imePrezimeInput;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel izaberiteTipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<KategorijaVeslaca> kategorijaComboBox;
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JTextField najboljeVremeInput;
    private javax.swing.JLabel nazivLabel;
    private javax.swing.JButton obrisiVeslacBtn;
    private javax.swing.JButton potvrdiAzuriranjeButton;
    private com.github.lgooddatepicker.components.DatePicker rodjenjeDatePicker;
    private javax.swing.JTextField tezinaInput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private com.github.lgooddatepicker.components.DatePicker upisDatePicker;
    private javax.swing.JTextField visinaInput;
    // End of variables declaration//GEN-END:variables
}
