package forme.prijava;

import com.formdev.flatlaf.FlatLightLaf;
import forme.agencija.GlavnaFormaAgencija;
import forme.klub.GlavnaFormaKlub;
import java.awt.Color;
import java.awt.Font;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.MatteBorder;
import klijent.Klijent;
import model.Nalog;
import model.VeslackiKlub;

/**
 *
 * @author luka
 */
public class PrijavaForma extends javax.swing.JFrame {

    /**
     * Creates new form PrijavaFormav2
     */
    public PrijavaForma() {
        
        try {
                UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (UnsupportedLookAndFeelException ex) {
                ex.printStackTrace();
            }
        
        initComponents();
        this.setLocationRelativeTo(this);
        setVisible(true);
        sifraGreskaLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        veslacIconLabel = new javax.swing.JLabel();
        dobrodosliLabel = new javax.swing.JLabel();
        prijavaLabel = new javax.swing.JLabel();
        korisnickoImeLabel = new javax.swing.JLabel();
        korisnickoImeInput = new javax.swing.JTextField();
        sifraKorisnikaLabel = new javax.swing.JLabel();
        sifraKorisnikaInput = new javax.swing.JPasswordField();
        sifraGreskaLabel = new javax.swing.JLabel();
        prijavaButton = new javax.swing.JButton();
        nemateNalogLabel = new javax.swing.JLabel();
        registracijaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(13, 146, 244));

        titleLabel.setFont(new java.awt.Font("JetBrains Mono", 3, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Prepoznaj i Preporuči Veslača");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dobrodosliLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        dobrodosliLabel.setText("DOBRODOŠLI NAZAD,");

        prijavaLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        prijavaLabel.setForeground(new java.awt.Color(153, 153, 153));
        prijavaLabel.setText("Prijavite se ");

        korisnickoImeLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        korisnickoImeLabel.setText("Korisničko Ime :");

        korisnickoImeInput.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        korisnickoImeInput.setForeground(new java.awt.Color(153, 153, 153));
        korisnickoImeInput.setText("Unesite korisničko ime...");
        korisnickoImeInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        korisnickoImeInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                korisnickoImeInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                korisnickoImeInputFocusLost(evt);
            }
        });
        korisnickoImeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnickoImeInputActionPerformed(evt);
            }
        });

        sifraKorisnikaLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        sifraKorisnikaLabel.setText("Šifra korisnika :");

        sifraKorisnikaInput.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        sifraKorisnikaInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sifraKorisnikaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifraKorisnikaInputActionPerformed(evt);
            }
        });

        sifraGreskaLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 18)); // NOI18N
        sifraGreskaLabel.setForeground(new java.awt.Color(255, 51, 51));
        sifraGreskaLabel.setText("Greška pri unosu šifre, pokušajte ponovo");

        prijavaButton.setBackground(new java.awt.Color(13, 146, 244));
        prijavaButton.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        prijavaButton.setForeground(new java.awt.Color(255, 255, 255));
        prijavaButton.setText("Prijavite se");
        prijavaButton.setBorder(null);
        prijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaButtonActionPerformed(evt);
            }
        });

        nemateNalogLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        nemateNalogLabel.setForeground(new java.awt.Color(51, 51, 51));
        nemateNalogLabel.setText("Nemate nalog?");

        registracijaButton.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        registracijaButton.setForeground(new java.awt.Color(255, 51, 51));
        registracijaButton.setText("Registrujte se");
        registracijaButton.setBorder(null);
        registracijaButton.setBorderPainted(false);
        registracijaButton.setContentAreaFilled(false);
        registracijaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registracijaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(nemateNalogLabel)
                        .addGap(26, 26, 26)
                        .addComponent(registracijaButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veslacIconLabel)
                            .addComponent(sifraGreskaLabel)
                            .addComponent(sifraKorisnikaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifraKorisnikaLabel)
                            .addComponent(korisnickoImeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(korisnickoImeLabel)
                            .addComponent(prijavaLabel)
                            .addComponent(dobrodosliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(veslacIconLabel)
                .addGap(18, 18, 18)
                .addComponent(dobrodosliLabel)
                .addGap(18, 18, 18)
                .addComponent(prijavaLabel)
                .addGap(27, 27, 27)
                .addComponent(korisnickoImeLabel)
                .addGap(34, 34, 34)
                .addComponent(korisnickoImeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(sifraKorisnikaLabel)
                .addGap(33, 33, 33)
                .addComponent(sifraKorisnikaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sifraGreskaLabel)
                .addGap(56, 56, 56)
                .addComponent(prijavaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nemateNalogLabel)
                    .addComponent(registracijaButton))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void korisnickoImeInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_korisnickoImeInputFocusGained
        // TODO add your handling code here:
        if (korisnickoImeInput.getText().equals("Unesite korisničko ime...")) {
            korisnickoImeInput.setText("");
        }
    }//GEN-LAST:event_korisnickoImeInputFocusGained

    private void korisnickoImeInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_korisnickoImeInputFocusLost
        // TODO add your handling code here:
        if (korisnickoImeInput.getText().isEmpty()) {
            korisnickoImeInput.setText("Unesite korisničko ime...");
        }
    }//GEN-LAST:event_korisnickoImeInputFocusLost

    private void korisnickoImeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnickoImeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnickoImeInputActionPerformed

    private void prijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaButtonActionPerformed
        // TODO add your handling code here:
        // Scenario: pogrešna šifra je uneta pa piše sifraGreskaLabel, ponovnim klikom ponovnim klikom na dugme
        sifraGreskaLabel.setVisible(false);

        if (korisnickoImeInput.getText().equals("Unesite korisničko ime...")) {
            korisnickoImeInput.setFont(new Font("Ubuntu", Font.ITALIC, 24));
            korisnickoImeInput.setForeground(new Color(255, 51, 51));
            korisnickoImeInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
        }

        if (sifraKorisnikaInput.getText().isEmpty() || sifraKorisnikaInput.getText().length() < 6) {
            sifraKorisnikaInput.setBorder(new MatteBorder(0, 0, 1, 0, new Color(255, 51, 51)));
            sifraGreskaLabel.setText("Greška pri unosu šifre, pokušajte ponovo");
            sifraGreskaLabel.setVisible(true);
        }
        
        Nalog ulogovaniNalog = null;
        try {
            ulogovaniNalog = Klijent.getInstance().login(new Nalog(null,0,null,null,null,null,korisnickoImeInput.getText(), sifraKorisnikaInput.getText()));
            System.out.println(ulogovaniNalog);
        } catch (Exception ex) {
            ex.printStackTrace();
            sifraGreskaLabel.setText("Nalog nije pronadjen pokušajte ponovo");
            sifraGreskaLabel.setVisible(true);
        }
        
        if (ulogovaniNalog != null) {
            Klijent.getInstance().setUlogovaniNalog(ulogovaniNalog);
            Klijent.getInstance().setOdjavaSignal(false);
            if(ulogovaniNalog instanceof VeslackiKlub){
                GlavnaFormaKlub gvk = new GlavnaFormaKlub();
            }else {
                GlavnaFormaAgencija gva = new GlavnaFormaAgencija();
            }
            
            this.dispose();

        }
    }//GEN-LAST:event_prijavaButtonActionPerformed

    private void registracijaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registracijaButtonActionPerformed
        // TODO add your handling code here:
        RegistracijaForma forma = new RegistracijaForma(this,true);
    }//GEN-LAST:event_registracijaButtonActionPerformed

    private void sifraKorisnikaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifraKorisnikaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifraKorisnikaInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrijavaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dobrodosliLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField korisnickoImeInput;
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JLabel nemateNalogLabel;
    private javax.swing.JButton prijavaButton;
    private javax.swing.JLabel prijavaLabel;
    private javax.swing.JButton registracijaButton;
    private javax.swing.JLabel sifraGreskaLabel;
    private javax.swing.JPasswordField sifraKorisnikaInput;
    private javax.swing.JLabel sifraKorisnikaLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel veslacIconLabel;
    // End of variables declaration//GEN-END:variables
}
