package operacije;

/**
 *
 * @author luka
 */
public enum Operacija {
    //Login
    PRIJAVA,
    //VeslackiKlub
    REGISTRACIJA_KLUB,
    KREIRANJE_KLUB,
    PROMENA_KLUB,
    PRETRAZIVANJE_KLUB,
    BRISANJE_KLUB,
    VRATI_SVE_KLUBOVE,
    
    //Agencija
    REGISTRACIJA_AGENCIJA,
    KREIRANJE_AGENCIJA,
    PROMENA_AGENCIJA,
    PRETRAZIVANJE_AGENCIJA,
    BRISANJE_AGENCIJA,
    
    //Veslac
    KREIRANJE_VESLAC,
    PROMENA_VESLAC,
    BRISANJE_VESLAC,
    PRETRAZIVANJE_VESLAC,
    VRATI_SVE_VESLACE,
    VRATI_VESLACA_PO_ID,
    
    //TAKMICENJE
    UBACIVANJE_TAKMICENJE,
    PRETRAZIVANJE_TAKMICENJE,
    BRISANJE_TAKMICENJE,
    
    // DRZAVA
    UBACIVANJE_DRZAVA,
    BRISANJE_DRZAVA,
    
    //PONUDA VESLACA
    KREIRANJE_PONUDE,
    PRETRAZIVANJE_PONUDE,
    PROMENA_PONUDE,
    BRISANJE_PONUDE,
    VRATI_SVE_PONUDE_KLUBA,
    VRATI_SVE_PONUDE_AGENCIJE,
    
    //KLUBTAKMICENJE
    VRATI_TAKMICENJA_KLUBA,
    
    PREKID,
    
    
}
