package operacije;

/**
 *
 * @author luka
 */
public enum Operacija {
    //Login
    PRIJAVA,
    //VeslackiKlub
    KREIRANJE_KLUB,
    PROMENA_KLUB,
    PRETRAZIVANJE_KLUB,
    BRISANJE_KLUB,
    VRATI_LISTU_SVI_VESLACKI_KLUB,
    VRATI_LISTU_VESLACKI_KLUB,
    
    //Agencija
    KREIRANJE_AGENCIJA,
    PROMENA_AGENCIJA,
    PRETRAZIVANJE_AGENCIJA,
    BRISANJE_AGENCIJA,
    VRATI_LISTU_SVE_AGENCIJE,
    VRATI_LISTU_AGENCIJE,
    
    //Veslac
    KREIRANJE_VESLAC,
    PROMENA_VESLAC,
    BRISANJE_VESLAC,
    PRETRAZIVANJE_VESLAC,
    VRATI_LISTU_SVI_VESLAC,
    VRATI_LISTU_VESLAC,
    
    //TAKMICENJE
    UBACIVANJE_TAKMICENJE,
    PRETRAZIVANJE_TAKMICENJE,
    BRISANJE_TAKMICENJE,
    VRATI_LISTU_TAKMICENJA,
    VRATI_LISTU_SVI_TAKMICENJA,
    
    // DRZAVA
    UBACIVANJE_DRZAVA,
    BRISANJE_DRZAVA,
    VRATI_LISTU_SVE_DRZAVE,
    VRATI_LISTU_DRZAVE,
    
    //PONUDA VESLACA
    KREIRANJE_PONUDE,
    PRETRAZIVANJE_PONUDE,
    PROMENA_PONUDE,
    BRISANJE_PONUDE,
    VRATI_LISTU_SVI_PONUDE_VESLACA,
    VRATI_LISTU_PONUDE_VESLACA,
    VRATI_POSLEDNJI_ID_PONUDE,
    
    //STAVKE PONUDE
    VRATI_SVE_STAVKE_PONUDE,
    
    //KLUBTAKMICENJE
    KREIRANJE_KLUB_TAKMICENJE,
    BRISANJE_KLUB_TAKMICENJE,
    VRATI_LISTU_KLUB_TAKMICENJA,
    PREBROJ_TAKMICENJA,
    
    PREKID, 
    
    
}
