package operacije;

/**
 *
 * @author luka
 */
public enum Operacija {
    //Login
    PRIJAVA,
    //VeslackiKlub
    KREIRANJE_KLUB,
    PROMENA_KLUB,
    PRETRAZIVANJE_KLUB,
    BRISANJE_KLUB,
    VRATI_SVE_KLUBOVE,
    VRATI_KLUB_PO_ID,
    
    //Agencija
    KREIRANJE_AGENCIJA,
    PROMENA_AGENCIJA,
    PRETRAZIVANJE_AGENCIJA,
    BRISANJE_AGENCIJA,
    VRATI_SVE_AGENCIJE,
    
    //Veslac
    KREIRANJE_VESLAC,
    PROMENA_VESLAC,
    BRISANJE_VESLAC,
    PRETRAZIVANJE_VESLAC,
    VRATI_SVE_VESLACE,
    VRATI_VESLACA_PO_ID,
    
    //TAKMICENJE
    UBACIVANJE_TAKMICENJE,
    PRETRAZIVANJE_TAKMICENJE,
    BRISANJE_TAKMICENJE,
    VRATI_TAKMICENJE_PO_ID,
    VRATI_SVA_TAKMICENJA,
    
    // DRZAVA
    UBACIVANJE_DRZAVA,
    BRISANJE_DRZAVA,
    VRATI_SVE_DRZAVE,
    
    //PONUDA VESLACA
    KREIRANJE_PONUDE,
    PRETRAZIVANJE_PONUDE,
    PROMENA_PONUDE,
    BRISANJE_PONUDE,
    VRATI_SVE_PONUDE_KLUBA,
    VRATI_SVE_PONUDE_AGENCIJE,
    VRATI_POSLEDNJI_ID_PONUDE,

    
    //STAVKE PONUDE
    VRATI_SVE_STAVKE_PONUDE,
    
    //KLUBTAKMICENJE
    OSVOJI_TAKMICENJE,
    BRISANJE_OSVOJENO_TAKMICENJE,
    VRATI_TAKMICENJA_KLUBA,
    PREBROJ_OSVOJENA_TAKMICENJA,
    
    PREKID, 
    
    
}
