
package common;


public enum Operacija {
    PRIJAVA,
    REGISTRACIJA_KLUB,
    KREIRANJE_KLUB,
    PROMENA_KLUB,
    BRISANJE_KLUB,
    REGISTRACIJA_AGENCIJA,
    KREIRANJE_AGENCIJA,
    PROMENA_AGENCIJA,
    BRISANJE_AGENCIJA,
    KREIRANJE_VESLAC,
    PROMENA_VESLAC,
    BRISANJE_VESLAC,
    
    
}
